export const MEALS = [
    {
      id: "1",
      name: "Phulka Chapati",
      image:"https://www.mydelicious-recipes.com/home/OGImage/234/MyDelicious-Recipes-Image/",
      description: "phulka chapati",
      quantity: 1,
      category: "chapati",
      price: 10,
    },
    {
      id: "2",
      name: "Pumpkin Chapati",
      image:"https://3.bp.blogspot.com/-EJUK_vr_Kis/VIPTsSOi4KI/AAAAAAABCL8/SZgDl6a3bdU/w1200-h630-p-k-no-nu/chapati.jpg",
      quantity: 1,
      description: "pumpkin chapati",
      category: "chapati",
      price: 10,
    },
    {
      id: "3",
      name: "mango pickle",
      image:"https://tse4.mm.bing.net/th?id=OIP.Cy_hW0_Y-LUY0C1eHOnvcQHaE8&pid=Api&P=0",
      description: " delicious mango pickle",
      quantity: 1,
      category: "pickle",
      price: 30,
    },

    {
      id: "4",
      name: "Carrot pickle",
      image:"https://tse1.mm.bing.net/th?id=OIP.ruQ6vZT_7nlvVFDuQTz9YgHaEK&pid=Api&P=0",
      description: " delicious carrot pickle",
      quantity: 1,
      category: "pickle",
      price: 30,
    },

    {
      id: "5",
      name: "lemon pickle",
      image:"https://tse4.mm.bing.net/th?id=OIP.TeQ37hlaBByUx3uCjlQBvQHaEK&pid=Api&P=0",
      description: " delicious lemon pickle",
      quantity: 1,
      category: "pickle",
      price: 30,
    },
    {
      id: "6",
      name: "Curd",
      description: " pure and fresh curd ",
      image:"https://tse3.mm.bing.net/th?id=OIP._P8HqyxJUsQZyo9nAbWhvQHaGH&pid=Api&P=0",
      category: "curd",
      quantity: 1,
      price: 80,
    },
    {
      id: "7",
      name: "Gulab Jamun",
      image:"https://tse2.mm.bing.net/th?id=OIP.eG3Qdl_ITBrQaOA7ch6rFgHaFY&pid=Api&P=0",
      description: "the best gulab jamun to have in your dish",
      quantity: 1,
      category: "sweet",
      price: 45,
    },
    {
      id: "8",
      name: "Lauki Halwa",
      image:"https://tse1.mm.bing.net/th?id=OIP.41vjZ8jr1fgsOheKKxeilwHaEK&pid=Api&P=0",
      description: "Lauki Halwa ",
      quantity: 1,
      category: "sweet",
      price: 100,
    },
    {
      id: "9",
      name: "Dhaba style daal",
      description: "dhaba style daal",
      image:"https://tse2.mm.bing.net/th?id=OIP.951Gha7oWYLiKu7g0898EQFNC7&pid=Api&P=0",
      category: "daal",
      quantity: 1,
      price: 100,
    },
    {
      id: "10",
      name: "Golden Yellow Lentil Dal with Curry",
      image:"https://tse2.mm.bing.net/th?id=OIP.HKtDhd3g9qo5YCaWB7U7GAHaE7&pid=Api&P=0",
      description: "delicious daal with curry",
      quantity: 1,
      category: "daal",
      price: 100,
    },
    {
      id: "11",
      name: "Matar paneer",
      image:"https://tse1.mm.bing.net/th?id=OIP.0RkR6z88pBeB2DGygh8gcwHaHa&pid=Api&P=0",
      description: "matar paneer",
      quantity: 1,
      category: "paneer dish",
      price: 100,
    },
    {
      id: "12",
      name: "Paneer 65",
      image:"https://tse4.mm.bing.net/th?id=OIP.YH03mSLzDi5kICwzJV9l7wHaE8&pid=Api&P=0",
      description: " delicious daal",
      quantity: 1,
      category: "paneer dish",
      price: 100,
    },
    {
      id: "13",
      name: "Butter Paneer Pulao",
      image:"https://tse2.mm.bing.net/th?id=OIP.uzQHmg7aD58Vx0Nw4Smw1wHaJQ&pid=Api&P=0",
      description: " delicious daal",
      quantity: 1,
      category: "paneer dish",
      price: 100,
    },
  ];